version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
  deploy:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c0:e6:e6:74:ac:0e:ad:1e:9e:cf:b9:78:63:ff:96:1e"
      - run: ssh-keyscan 13.67.61.14 >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: ssh sowfkun@13.67.61.14 "cd /home/sowfkun/lapcity/webproject; git fetch; git commit -m 'update code when master change'; git merge ";
workflows:
  test-ci:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master