version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e9:93:45:b9:d9:88:ae:b7:b3:e3:66:bf:d2:2e:7c:6f"
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh sowfkun@13.67.61.14 "cd /home/sowfkun/lapcity/webproject; git fetch; git commit -m 'update code when master change'; git merge ";
workflows:
  test-ci:
    jobs:
      - build
      - deploy:
          requires:
            - build