version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
    deployment:
      production:
        branch: master
          run:
            name: Update code on Server
            command:  |
              scp -r sowfkun/webproject sowfkun@13.67.61.14:/home/sowfkun/lapcity/webproject
workflows:
  test-ci:
    jobs:
      - build
      - deployment